server:
  port: 8888

spring:
  application:
    name : configServer
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/alikarimi8765/spring-cloud-sample.git
          search-paths:
            - config*
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761